name: CI Spring Boot

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Especificamos el directorio de trabajo donde está el código de Spring Boot
    defaults:
      run:
        working-directory: ./rotompediabackend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos de ejecución a gradlew
      run: chmod +x ./gradlew

    - name: Construir y probar con Gradle (Build & Test)
      run: ./gradlew build