name: CI Spring Boot (solo eco)

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      
name: Hacer eco
      run: echo "Esto es un eco - El pipeline ya no compila, solo imprime este mensaje"